# Generated by Django 4.2 on 2023-08-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
        migrations.AddField(
            model_name='post',
            name='img_cover',
            field=models.CharField(default='echo', max_length=1000),
            preserve_default=False,
        ),
    ]
