# Generated by Django 4.2 on 2023-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_intro_post_img_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_cover',
            new_name='imagecover',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='empty', max_length=1000),
            preserve_default=False,
        ),
    ]
