# Generated by Django 4.2 on 2023-11-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_title', models.CharField(max_length=30)),
                ('home_title', models.CharField(max_length=50)),
                ('home_paragraph', models.TextField(max_length=300)),
                ('about_blog', models.TextField(max_length=2500)),
                ('about_author', models.TextField(max_length=2500)),
                ('instagram_feed', models.CharField(max_length=2500)),
                ('copyright', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
