# Generated by Django 4.2 on 2023-11-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_info_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='contact_email',
            field=models.EmailField(default='admin@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='home_paragraph',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram_feed',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
