# Generated by Django 4.2 on 2023-11-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_info_contact_email_alter_info_home_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Informations'},
        ),
    ]
