# Generated by Django 4.2 on 2023-11-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_info_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('subscribed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-subscribed'],
            },
        ),
        migrations.AlterField(
            model_name='info',
            name='copyright',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['-subscribed'], name='blog_newsle_subscri_8cead6_idx'),
        ),
    ]
