# Generated by Django 4.2 on 2023-11-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_newsletter_alter_info_copyright_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=50)),
                ('link_slug', models.SlugField(max_length=200, unique=True)),
                ('link_section', models.CharField(choices=[('WL', 'Website links'), ('OL', 'Other links'), ('SL', 'Social links')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Footer links',
                'ordering': ['link_section'],
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of technology.', max_length=30)),
                ('icon', models.ImageField(height_field=32, help_text='32x32 logo icon.', upload_to='', width_field=32)),
                ('description', models.TextField(help_text='Just core description of service-related usage.', max_length=300)),
                ('url', models.URLField(help_text='Website of the technology.', max_length=150)),
                ('show', models.BooleanField(default=True, help_text='Should be rendered?')),
            ],
            options={
                'verbose_name_plural': 'Techstack',
                'ordering': ['show'],
            },
        ),
        migrations.AlterField(
            model_name='info',
            name='about_author',
            field=models.TextField(help_text='Some personal informations.', max_length=2500),
        ),
        migrations.AlterField(
            model_name='info',
            name='about_blog',
            field=models.TextField(help_text='Blog vision and roadmap.', max_length=2500),
        ),
        migrations.AlterField(
            model_name='info',
            name='base_title',
            field=models.CharField(help_text='Navigation spot title.', max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='contact_email',
            field=models.EmailField(help_text='Email for contact.', max_length=254),
        ),
        migrations.AlterField(
            model_name='info',
            name='copyright',
            field=models.CharField(blank=True, help_text='Bottom copyright text.', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='home_paragraph',
            field=models.TextField(help_text='Landing page short web introduction.', max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='home_title',
            field=models.CharField(help_text='Browser tab and huge landing page title.', max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram_feed',
            field=models.CharField(blank=True, help_text='Instagram embeded code.', max_length=2500),
        ),
        migrations.AddIndex(
            model_name='techstack',
            index=models.Index(fields=['show'], name='blog_techst_show_8d994f_idx'),
        ),
        migrations.AddIndex(
            model_name='footer',
            index=models.Index(fields=['link_section'], name='blog_footer_link_se_503877_idx'),
        ),
    ]
