# Generated by Django 4.2 on 2023-11-04 22:36

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_footer_techstack_alter_info_about_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='template_body',
            field=mdeditor.fields.MDTextField(default='body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='template_title',
            field=models.CharField(default=models.CharField(max_length=50), max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram_feed',
            field=models.TextField(blank=True, help_text='Instagram embeded code.', max_length=2500),
        ),
    ]
