# Generated by Django 4.2 on 2023-11-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_footer_template_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='icon',
            field=models.ImageField(help_text='Logo icon.', upload_to='techstack/'),
        ),
    ]
