# Generated by Django 4.2 on 2023-11-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_techstack_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='about_author',
            field=models.TextField(help_text='Some informations about author.', max_length=2500),
        ),
        migrations.AlterField(
            model_name='info',
            name='about_blog',
            field=models.TextField(help_text='Blog vision and summary.', max_length=2500),
        ),
        migrations.AlterField(
            model_name='info',
            name='home_paragraph',
            field=models.TextField(help_text='Landing page short introduction.', max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='home_title',
            field=models.CharField(help_text='Landing page title.', max_length=50),
        ),
    ]
