# Generated by Django 4.2 on 2023-11-07 02:34

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_info_about_author_alter_info_about_blog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ['-link_section'], 'verbose_name_plural': 'Footer links'},
        ),
        migrations.RemoveIndex(
            model_name='footer',
            name='blog_footer_link_se_503877_idx',
        ),
        migrations.AddField(
            model_name='footer',
            name='link_url',
            field=models.URLField(blank=True, help_text='URL for social.'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_slug',
            field=models.SlugField(blank=True, help_text='Slug for website/other.', max_length=200),
        ),
        migrations.AlterField(
            model_name='footer',
            name='template_body',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='template_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='footer',
            index=models.Index(fields=['-link_section'], name='blog_footer_link_se_c44637_idx'),
        ),
    ]
