# Generated by Django 4.2 on 2023-11-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_footer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
