# Generated by Django 4.2 on 2023-11-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='instagram_feed',
            field=models.TextField(blank=True, help_text='Instagram embeded code.', max_length=40000),
        ),
    ]
