# Generated by Django 4.2 on 2023-11-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_info_instagram_feed_alter_info_copyright'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['id'], 'verbose_name_plural': 'Techstack'},
        ),
        migrations.RemoveIndex(
            model_name='techstack',
            name='blog_techst_show_8d994f_idx',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='show',
        ),
        migrations.AlterField(
            model_name='techstack',
            name='description',
            field=models.TextField(help_text='Just core description of service-related usage.', max_length=2500),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='techstack',
            index=models.Index(fields=['id'], name='blog_techst_id_ad939e_idx'),
        ),
    ]
