# Generated by Django 4.2 on 2023-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_footer_options_alter_homelab_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeLabElement',
        ),
        migrations.AlterModelOptions(
            name='homelab',
            options={'verbose_name_plural': 'Homelab'},
        ),
        migrations.AddField(
            model_name='homelab',
            name='lab_image',
            field=models.ImageField(default='mylab.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
