# Generated by Django 4.1.6 on 2023-03-01 09:53

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blogcore', '0002_post_footnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='footnotes',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated tags. Use quotes for multiple words and lowercase letters.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
